### ISSUE TITLE
Gutter signs show up then disappear

### ISSUE THREAD

**Issue by megalithic** [iamcco/coc-diagnostic#1]
@iamcco - With the `mix_credo` linter (thanks for making that one official!), the gutter signs i set for diagnostics in `coc-settings.json` show up, then disappear a second or so later..

<img width="971" alt="Screenshot 2019-05-10 15 34 04" src="https://user-images.githubusercontent.com/3678/57555181-31f54b00-7339-11e9-91d5-63dcf0fac13f.png">

Confirmed that `elixir-ls` diagnostics and their gutter signs work and stay in place.

**Comment by iamcco** [comment]
Can't reproduce, please test with minimum vimrc.
