### ISSUE TITLE
Passing arguments to shellcheck

### ISSUE THREAD

**Issue by Mendess2526** [iamcco/coc-diagnostic#10]
My `coc-settings.json` file looks like this
```json
  "diagnostic-languageserver.filetypes": {
    "sh": "shellcheck"
  }
```
But I want to pass `-x` to `shellcheck`, how do I do this? Is it possible?

**Comment by iamcco** [comment]
copy the shellcheck linter config and change what you need.

**Comment by unphased** [comment]
All I had to do was add ` -x` to that `sh` prop there.
