### ISSUE TITLE
how to disable diagnostic on certain filetypes?

### ISSUE THREAD

**Issue by wangsongiam** [iamcco/coc-diagnostic#11]
Hi thanks for this great extension.

Just wondering if it's possible to disable diagnostics on some filetypes? for example, markdown.

I know `"diagnostic.enable": false` in `coc-settings.json` works  but that would disable every filetype.

also tried
```vim
autocmd FileType markdown let b:coc_suggest_disable = 1
```
but that only works for suggestions. Would be great to know if there's another flag works for diagnostics.

**Comment by iamcco** [comment]
This extension only enable for the filetypes by your configuration.

``` jsonc
{
   // diagnostic-languageserver
  "diagnostic-languageserver.filetypes": {
    "vim": "vint",
    "email": "languagetool",
    "markdown": [ "write-good", "markdownlint" ],
    "sh": "shellcheck",
    "elixir": ["mix_credo", "mix_credo_compile"],
    "eelixir": ["mix_credo", "mix_credo_compile"],
    "php": "phpcs"
    ...
  }
}
```

**Comment by wangsongiam** [comment]
seems overriding the filetypes to empty works, thanks!
