### ISSUE TITLE
警告信息全都高亮

### ISSUE THREAD

**Issue by FlamesCN** [iamcco/coc-diagnostic#116]
**Describe the bug**
启用插件后警告信息全都高亮，关闭后显示正常。如何设置只有第一个字符高亮，或关闭该功能？

启用时：整个警告区域全高亮
![image](https://user-images.githubusercontent.com/12966659/137101252-8e2986d1-95fb-4f82-8581-3314472e4ce2.png)
关闭后：只有第一个字符位置高亮
![image](https://user-images.githubusercontent.com/12966659/137101533-4490c285-710d-492f-9392-341f0a072d01.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04

**Comment by iamcco** [comment]
coc 高亮的问题，你需要换个主题或自己设置 coc 高亮组.

查看帮助 `:h coc-highlights`

或者试试下面的我的配置

```
  autocmd ColorScheme * highlight! CocUndercurl cterm=undercurl gui=undercurl
  " do not underline error/info/hit lines
  autocmd ColorScheme * highlight! link CocErrorHighlight CocUndercurl
  autocmd ColorScheme * highlight! link CocWarningHighlight CocUndercurl
  autocmd ColorScheme * highlight! link CocInfoHighlight CocUndercurl
  autocmd ColorScheme * highlight! link CocHintHighlight CocUndercurl
```
