### ISSUE TITLE
[sh] diagnostic handle fail: [shellcheck] Unexpected end of JSON input

### ISSUE THREAD

**Issue by goldcome** [iamcco/coc-diagnostic#117]
shellcheck linter not work，how can i do? thank you.

coc-setting.json:

```
{
  "diagnostic-languageserver.mergeConfig": true,
  "diagnostic-languageserver.filetypes": {
    "sh": "shellcheck"
  },
  "diagnostic-languageserver.formatFiletypes": {
    "sh": "shfmt"
  }
}
```

:CocCommand workspace.showOutput

```
[Error  - 10:22:05 AM] [sh] diagnostic handle fail: [shellcheck] Unexpected end of JSON input
```

shellcheck -V
ShellCheck - shell script analysis tool
version: 0.4.6
license: GNU General Public License, version 3
website: http://www.shellcheck.net

**Comment by goldcome** [comment]
may be https://github.com/iamcco/coc-diagnostic/blob/86b7937d8cc3b3f98e4982adc51aa83ee9200659/src/config.ts#L44 json1 to json

**Comment by lithammer** [comment]
`json1` was added in v0.7.0.

https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md#v070---2019-07-28

**Comment by goldcome** [comment]
yes, you are right@lithammer，my shellchek version too old! thank you!
