### ISSUE TITLE
Provide default configurations for common linters

### ISSUE THREAD

**Issue by languitar** [iamcco/coc-diagnostic#14]
I am evaluating whether I should migrate my current vim setup from using ALE for linting to this coc extension. What is currently a problem for me is the lack of default configurations for linters. It would be nice if there was a set of preconfigured linters or at least an example from where to copy and paste definitions for common linters. Maybe this could be sourced from the ALE linter definitions?

**Comment by iamcco** [comment]
There are some preconfigured linters 

https://github.com/iamcco/diagnostic-languageserver/wiki/Linters

https://github.com/iamcco/coc-diagnostic/blob/master/src/config.ts

You have to enable by `diagnostic-languageserver.filetypes` option.

This extension will not enable any linters for you by default.

**Comment by languitar** [comment]
I didn't know that Wiki page exists. Having that as a reference would be fine for me. Maybe linking it more prominently in the Readmes would help discovering this page, though.
