### ISSUE TITLE
[advice] how about use json to restore config.ts?

### ISSUE THREAD

**Issue by Freed-Wu** [iamcco/coc-diagnostic#141]
Like <https://github.com/voldikss/vim-browser-search/blob/master/assets/json/engines.json>? We can use <https://github.com/voldikss/vim-browser-search/blob/master/.github/workflows/jq.yml> to sort them in every PR.

**Comment by iamcco** [comment]
JSON has too many limitation to the syntax.

**Comment by Freed-Wu** [comment]
You mean comment or trailing comma? I seldom find comment in config.ts . You can consider use a formatter to format trailing comma or simply use jsonc (aka jaon5 or hjson)
