### ISSUE TITLE
How to install using vim-plug to work properly

### ISSUE THREAD

**Issue by raahii** [iamcco/coc-diagnostic#15]
I tried to install this extension like:
```
Plug 'iamcco/coc-diagnostic', {'do': 'yarn install --frozen-lockfile'}
```
Installation itself is succeeded but linting/formatting didn't work. I confirmed the extension is activated on `CocList extensions`. So, when I executed `:CocInstall coc-diagnostic`, the features started to work properly.

How do I install this plugin to work properly? 
Thank you for developing this awesome plugin.

**Comment by iamcco** [comment]
Use `Plug 'iamcco/coc-diagnostic', {'do': 'yarn install --frozen-lockfile && yarn build'}`

**Comment by raahii** [comment]
It worked! Thank you.

**Comment by varac** [comment]
I'm confused, what's the difference between `:CocInstall coc-diagnostic` and using Plug as shown above ?

**Comment by iamcco** [comment]
@varac `CocInstall` install extension from npm, the package in npm is build already.
