### ISSUE TITLE
eslint not working

### ISSUE THREAD

**Issue by miuirussia** [iamcco/coc-diagnostic#17]
eslint v6.8.0

```
diagnostic handle fail: [eslint] Unexpected end of JSON input
```

**Comment by iamcco** [comment]
Can not reproduce. Run `eslint --format json test-target-file.js` to see what happend.

**Comment by miuirussia** [comment]
[{"filePath":"test-target-file.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]

**Comment by iamcco** [comment]
Those output seems fine. I can't reproduce this issue. It works well for me with eslint@6.8.0

**Comment by iamcco** [comment]
Try regex config to see if it work for you:

``` jsonc
  "eslint": {
    "command": "./node_modules/.bin/eslint",   // this will find local eslint first, if local eslint not found, it will use global eslint
    "rootPatterns": [".git"],
    "debounce": 100,
    "args": [ "--stdin", "--no-color" ],
    "offsetLine": 0,
    "offsetColumn": 0,
    "sourceName": "eslint",
    "formatLines": 1,
    "formatPattern": [
      "^\\s*(\\d+):(\\d+)\\s+([^ ]+)\\s+(.*?)\\s+([^ ]+)$",
      {
        "line": 1,
        "column": 2,
        "message": [4, " [", 5, "]" ],
        "security": 3
      }
    ],
    "securities": {
      "error": "error",
      "warning": "warning"
    }
  }
```

**Comment by miuirussia** [comment]
Result:
```
diagnostic handle fail: [eslint] spawn eslint ENOENT
```

**Comment by iamcco** [comment]
It seems it eslint command not available.

**Comment by miuirussia** [comment]
But it available in shell in that path

**Comment by iamcco** [comment]
What about run `:!eslint --version` in you vim.

**Comment by miuirussia** [comment]
Yes, no in path for vim. I think plugin need a more clear description of the error (like - no exec in path)

**Comment by miuirussia** [comment]
Fixed, changed "rootPatterns" to ["package.json"]
