### ISSUE TITLE
HTML linter is not working

### ISSUE THREAD

**Issue by Neur1n** [iamcco/coc-diagnostic#18]
### Environment
OS: Windows 10
Neovim: 

### Configuration
In my `coc-settings.json`:
```json
  "diagnostic-languageserver.filetypes": {
    "html": "tidy",
    "vim": "vint"
  },
  "diagnostic-languageserver.linters": {
    "tidy": {
      "command": "tidy",
      "args": ["-e", "-q"],
      "rootPatterns": [".git/"],
      "debounce": 100,
      "offsetLine": 0,
      "offsetColumn": 0,
      "sourceName": "tidy",
      "formatLines": 1,
      "formatPattern": [
        "^.*(\\d+).*(\\d+)\\s+-\\s+([^:]+):\\s+(.*)$",
        {
          "line": 1,
          "column": 2,
          "endLine": 1,
          "endColumn": 2,
          "message": [4],
          "security": 3
        }
      ]
    }
```

As for the pattern, here is an example output when I run `tidy -e -q test.html` from terminal:
```
line 25 column 3 - Error: <dic> is not recognized!
```

But nothings happens while editing the file and an error is present.

Additionally, previously the `formatPattern` was not configured in my `coc-settings.json` file, and when I type `:CocInfo` there are lines saying that:
```
## Output channel: diagnostic-languageserver

[Error  - 9:15:03 PM] [html] diagnostic handle fail: [tidy] missing formatLines or formatPattern
```

So I think it is working in background, but nothing pops up after I configured `formatPattern`.

**Comment by iamcco** [comment]
- add `isStderr: true`
- change `formatPattern`
- add `securities`

``` jsonc
  "diagnostic-languageserver.linters": {
    "tidy": {
      "command": "tidy",
      "args": ["-e", "-q"],
      "rootPatterns": [".git/"],
      "isStderr": true,
      "debounce": 100,
      "offsetLine": 0,
      "offsetColumn": 0,
      "sourceName": "tidy",
      "formatLines": 1,
      "formatPattern": [
        "^.*?(\\d+).*?(\\d+)\\s+-\\s+([^:]+):\\s+(.*)$",
        {
          "line": 1,
          "column": 2,
          "endLine": 1,
          "endColumn": 2,
          "message": [4],
          "security": 3
        }
      ],
      "securities": {
        "Error": "error",
        "Warning": "warning"
      }
    }
  }
```

**Comment by Neur1n** [comment]
Thanks for your effort, but it doesn't work. Allow me to provide more details.

**Tidy**: version 5.3.14, comes with neovim.
**Test file**: a `test.html` with a single line `<dic` inside.
**Terminal output**: with `tidy -e -q test.html`
```
line 2 column 1 - Warning: <dic> end of file while parsing attributes
line 1 column 1 - Error: <dic> is not recognized!
line 2 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: discarding unexpected <dic>
line 2 column 1 - Warning: inserting missing 'title' element
```

And while testing, no coc plugins but only coc-diagnotic is loaded.

**Comment by Neur1n** [comment]
Alright, I've test it on a Linux machine, and it worked. So far, the conclusion is that it doesn't on Windows, neither tidy nor vint which both work on Linux (Ubuntu 16.04).

**Comment by iamcco** [comment]
Please open an new issue with log info.

**Comment by Neur1n** [comment]
When you say "log info", do you mean the output of `:CocOpenLog`?

**Comment by iamcco** [comment]
Also `:CocInfo`
