### ISSUE TITLE
Error output from diagnostic-languageserver: diagnostic handle fail: spawn shellcheck ENOENT

### ISSUE THREAD

**Issue by AleksanderPopov** [iamcco/coc-diagnostic#2]
Hello, I'm trying to use your plugin to use coc.nvim for linting instead of ale, here is my coc-settings:

```
{
  "languageserver": {
    "golang": {
      "command": "bingo",
      "filetypes": ["go"],
      "rootPatterns": ["go.mod"]
    },
    "sh": {
      "command": "bash-language-server",
      "args": ["start"],
      "filetypes": ["sh"],
      "ignoredRootPaths": ["~"]
    },
    "dockerfile": {
      "command": "docker-langserver",
      "filetypes": ["dockerfile"],
      "args": ["--stdio"]
    }
  },
  "diagnostic-languageserver.filetypes": {
    "email": "languagetool",
    "markdown": [ "write-good", "markdownlint" ],
    "sh": "shellcheck",
    "elixir": ["mix_credo", "mix_credo_compile"],
    "eelixir": ["mix_credo", "mix_credo_compile"]
  },
  "diagnostic-languageserver.formatFiletypes": {
    "dart": "dartfmt",
    "elixir": "mix_format",
    "eelixir": "mix_format"
  }
}
```

When I open .sh file I see following error:
`[coc.nvim] Error output from diagnostic-languageserver: [sh] diagnostic handle fail: spawn shellcheck ENOENT`
the same for .md file:
`[coc.nvim] Error output from diagnostic-languageserver: [markdown] diagnostic handle fail: spawn markdownlint ENOENT`

**Comment by iamcco** [comment]
Have you install shellcheck and markdownlint-cli ?

**Comment by AleksanderPopov** [comment]
Actully I just installed `markdownlint-cli` ( previosly it was `markdownlint` ) and `shellcheck` is already there, but seems like it conflicting with something in zsh...Anyways, after installing `markdownlint-cli` there are still errors ( but linting seems to work through )

![Screen Shot 2019-05-21 at 8 30 37 AM](https://user-images.githubusercontent.com/21224705/58070789-142eae00-7ba3-11e9-939a-8a5622627ee0.png)

**Comment by iamcco** [comment]
your config "markdown": [ "write-good", "markdownlint" ] use two linters so you have to inatall writw-good too.

**Comment by AleksanderPopov** [comment]
It works now, thank you!
