### ISSUE TITLE
Question regarding post-installation process

### ISSUE THREAD

**Issue by pyrr** [iamcco/coc-diagnostic#24]
With shellcheck in path I just do CocInstall coc-diagnostic and then add the following lines to the CocConfig.

"diagnostic-languageserver.linters": {
  "sh": "shellcheck",
}

That should be it right ?

**Comment by iamcco** [comment]
https://github.com/iamcco/coc-diagnostic#config

**Comment by pyrr** [comment]
Yeah I looked at that.
I'm still confused, sorry if I seem inattentive.
Do I need to config shellcheck first like shown here ?
https://github.com/iamcco/diagnostic-languageserver#how-to-config-a-new-linter

**Comment by iamcco** [comment]
"diagnostic-languageserver.filetypes": {
    "sh": "shellcheck"
  }

**Comment by pyrr** [comment]
I fully get it now.
I tried configuring vint first and since I have a version which apparently doesn't work ( saw the other issue related to vint ) I was convinced I was configuring coc-diagnostic the wrong way. 
I first thought filetypes was just for limiting the linters to specific file types.

Thank you.
