### ISSUE TITLE
Allow populate location list on demand

### ISSUE THREAD

**Issue by przepompownia** [iamcco/coc-diagnostic#29]
This extension overrides currently watched location list. It annoys when watching some manually created list so I have set `"diagnostic.locationlist": false`.

However in some cases the possibility of manual populating the list would be useful. 

Please create an action that triggers populating the list one time.

**Comment by iamcco** [comment]
It's coc.nvim behavior，this extension just implement the LSP protocol for support diagnostics. You can use `:CocList diagnostics` to open diagnostics list.
