### ISSUE TITLE
I just can't install it

### ISSUE THREAD

**Issue by lifeBalance** [iamcco/coc-diagnostic#35]
I have an updated version of Coc.vim. I run `:CocInstall coc-diagnostic` and then add the following to my `coc-settings.json`:
```json
"diagnostic-languageserver.filetypes": {
  "sh": "shellcheck"
},
"diagnostic-languageserver.formatFiletypes": {
  "sh": "shfmt"
}
```
Every time I start Neovim I get an error: 
```
[coc.nvim] settings file parse error, run ':CocList diagnostics'
```
I run `:CocList diagnostics` and I get:
```
 /Users/bob/.config/nvim/coc-settings.json:1:38 Error [config] end of file expected
```

**Comment by iamcco** [comment]
coc-settings.json should be valid json
