### ISSUE TITLE
Option to change the PhpCs and PhpCbf standard

### ISSUE THREAD

**Issue by marioy47** [iamcco/coc-diagnostic#37]
Hello and thanks for this excellent extension.

I'm trying to use the extension on a WordPress project which has its [own format standard](https://github.com/WordPress/WordPress-Coding-Standards) with no success. 

I can configure the standard just fine by placing a `phpcs.xml.dist` file much like [this one](https://github.com/WordPress/gutenberg/blob/master/phpcs.xml.dist) in the root of my project, so when I execute `./vendor/bin/phpcs` and `./vendor/bin/phpcbf` the code gets linted and formatted. 

So my request would be for a way to change the args of the linter and formatter since they seem to be fixed: https://github.com/iamcco/coc-diagnostic/blob/master/src/config.ts#L136) 

Thanks in advance

**Comment by iamcco** [comment]
There are just default linters, you can copy and config your own linter with 'diagnostic-languageserver.linters' option.
