### ISSUE TITLE
Executing a the local phpcbf command does not fix files

### ISSUE THREAD

**Issue by marioy47** [iamcco/coc-diagnostic#38]
Hello,

After much struggle I was able to make `phpcs` lint my  WordPress files. 

The problem now is, is that `phpcbf` (The formatter) is not taking the local project configuration. The files get formatted but not to the correct standard.

This is my complete `coc-settings.json`:

```json
{
  "coc.preferences.formatOnSaveFiletypes": ["php", "json"],
  "diagnostic-languageserver.filetypes": {
    "php": ["phpcs"]
  },
  "diagnostic-languageserver.linters": {
    "phpcs": {
      "command": "./vendor/bin/phpcs",
      "debounce": 100,
      "rootPatterns": ["composer.json", "composer.lock", "vendor", ".git"],
      "args": ["--report=emacs", "-s", "-"],
      "offsetLine": 0,
      "offsetColumn": 0,
      "sourceName": "phpcs",
      "formatLines": 1,
      "formatPattern": [
        "^.*:(\\d+):(\\d+):\\s+(.*)\\s+-\\s+(.*)(\\r|\\n)*$",
        {
          "line": 1,
          "column": 2,
          "message": 4,
          "security": 3
        }
      ],
      "securities": {
        "error": "error",
        "warning": "warning"
      }
    }
  },
  "diagnostic-languageserver.formatFiletypes": {
    "php": "phpcbf"
  },
  "diagnostic-languageserver.formatters": {
    "phpcbf": {
      "command": "./vendor/bin/phpcbf",
      "rootPatterns": ["composer.json", "composer.lock", "vendor", ".git"],
      "args": ["-"]
    }
  }
}
```

**Comment by iamcco** [comment]
I do not use phpcbf so I don't know how to do that. Maybe you can add args or something to tell phpcbf to use your local configuration.

**Comment by marioy47** [comment]
I think I made some progress, but still no solution.

I added `"intelephense.format.enable": false,` to `coc-settings.json` and changed the `phpcbf` formater config to 

```json
  "diagnostic-languageserver.formatters": {
    "phpcbf": {
      "command": "./vendor/bin/phpcbf",
      "rootPatterns": ["composer.json", "composer.lock", "vendor", ".git"],
      "args": ["%file"],
      "isStdout": false,
      "doesWriteToFile": true
    }
  }
```

And now the files get formated but no loaded in the buffer.

The breaktrough is that I get the following error:
![vim-error](https://user-images.githubusercontent.com/3419025/83534774-e1f2a480-a4b6-11ea-8ec9-7d6e08d2b7bd.png)

So it looks like the `phpcbf` fixer is takes longer that normal.

is there  a way to increment the timeout so I can verify this?

**Comment by mkindred** [comment]
I'm having the same issue. phpcs works great, and phpcbf is making the corrections, but the saved file isn't loaded to the buffer.

![210524_coc_phpcbf_issues](https://user-images.githubusercontent.com/1648817/119387669-3fb76800-bc97-11eb-8790-a23210f5493f.gif)

**Comment by mkindred** [comment]
I've tried several combinations of isStdout and doesWriteToFile, and I can't quite get there. Here is my coc-settings.json file:

```
{
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "javascriptreact",
    "javascriptreact.html",
    "html",
    "json",
    "php",
    "yaml"
  ],
  "intelephense.format.enable": false,
  "diagnostic-languageserver.filetypes": {
    "php": "phpcs"
  },
  "diagnostic-languageserver.linters": {
    "phpcs": {
      "command": "phpcs",
      "debounce": 300,
      "rootPatterns": ["composer.lock", "vendor", ".git"],
      "args": ["--report=emacs", "-s", "-"],
      "offsetLine": 0,
      "offsetColumn": 0,
      "sourceName": "phpcs",
      "formatLines": 1,
      "formatPattern": [
        "^.*:(\\d+):(\\d+):\\s+(.*)\\s+-\\s+(.*)(\\r|\\n)*$",
        {
          "line": 1,
          "column": 2,
          "message": 4,
          "security": 3
        }
      ],
      "securities": {
        "error": "error",
        "warning": "warning"
      }
    }
  },
  "diagnostic-languageserver.formatFiletypes": {
    "php": "phpcbf"
  },
  "diagnostic-languageserver.formatters": {
    "phpcbf": {
      "command": "phpcbf",
      "rootPatterns": ["composer.lock", "vendor", ".git"],
      "args": ["--standard=./phpcs.xml", "%file"],
      "isStdout": false,
      "isStderr": false,
      "doesWriteToFile": true
    }
  },
  "git.enableGutters": false,
  "prettier.singleQuote": true
}
```
With this, I get the option to re-load the corrected file. But if I use the following, nothing happens.
```
  "diagnostic-languageserver.formatFiletypes": {
    "php": "phpcbf"
  },
  "diagnostic-languageserver.formatters": {
    "phpcbf": {
      "command": "phpcbf",
      "rootPatterns": ["composer.lock", "vendor", ".git"],
      "args": ["--standard=./phpcs.xml", "%file"],
      "isStdout": false,
      "isStderr": true,
      "doesWriteToFile": true
    }
  },
```

**Comment by mkindred** [comment]
Running `phpcbf test.php` from the command line does work, and it correctly picks up the appropriate phpcs.xml.

**Comment by iamcco** [comment]
what's `doesWriteToFile` options? coc-diagnostic doesn't support such option.

you have to make sure `phpcbf` command does not write change to disk and output format content to stdout or stderr. then set the stdout or stderr to true.

**Comment by mkindred** [comment]
I found doesWriteToFile under 'formatters field' at https://github.com/iamcco/diagnostic-languageserver

Yes, I'm trying to learn how to direct phpcbf output to stdout.

**Comment by iamcco** [comment]
> I found doesWriteToFile under 'formatters field' at https://github.com/iamcco/diagnostic-languageserver


ohhhhhhh my fault.

**Comment by yaegassy** [comment]
@iamcco Is it possible to pass `stdin` in "diagnostic-langserver"?

If you can pass it as stdin, this problem may be solved.

```
$ cat sample.php
<?php

declare(strict_types=1);

function dummy() {
    return "dummy";
}
$ cat sample.php | phpcbf
<?php

declare(strict_types=1);

function dummy()
{
    return "dummy";
}
```

**Comment by iamcco** [comment]
> @iamcco Is it possible to pass `stdin` in diagnostic-langserver's "formatter"?
> 
> If you can pass it as stdin, this problem may be solved.
> 
> ```
> $ cat sample.php
> <?php
> 
> declare(strict_types=1);
> 
> function dummy() {
>     return "dummy";
> }
> $ cat sample.php | phpcbf
> <?php
> 
> declare(strict_types=1);
> 
> function dummy()
> {
>     return "dummy";
> }
> ```

Yep, by default it use the stdin.

so it maybe works change the `%file` to `%filepath`:

```
"diagnostic-languageserver.formatters": {
    "phpcbf": {
      "command": "phpcbf",
      "rootPatterns": ["composer.lock", "vendor", ".git"],
      "args": ["--standard=./phpcs.xml", "%filepath"],
      "isStdout": true,
      "isStderr": false,
      "doesWriteToFile": false
    }
  },
```

**Comment by yaegassy** [comment]
I used `%filepath` and ran it in the same file as this comment. https://github.com/iamcco/coc-diagnostic/issues/38#issuecomment-847637890

Unfortunately, there seems to be no change in "newText" :(

```
linter run args: ["/Users/yaegassy/_Dev/php/slim4php8/sample.php"]
[Trace - 17:09:43] Received response 'textDocument/formatting - (4)' in 81ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 9,
                "character": 0
            }
        },
        "newText": "<?php\n\ndeclare(strict_types=1);\n\nfunction dummy() {\n    return \"dummy\";\n}\n"
    }
]
```

**Comment by iamcco** [comment]
https://github.com/iamcco/diagnostic-languageserver/blob/master/src/handles/handleFormat.ts#L50

seems like I know what happen. need to fix it.

**Comment by yaegassy** [comment]
@iamcco I tried to skip that control part in diagnostic-languageserver and it was formatted correctly in phpcbf

**setting**

```
// ...snip
    "phpcbf": {
      "command": "phpcbf",
      "rootPatterns": ["composer.json", "composer.lock", "vendor", ".git"],
      "isStdout": true,
      "isStderr": false
    }
// ..snip
```

**log(OK)**

```
linter run args: []
[Trace - 18:13:24] Received response 'textDocument/formatting - (3)' in 84ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 9,
                "character": 0
            }
        },
        "newText": "<?php\n\ndeclare(strict_types=1);\n\nfunction dummy()\n{\n    return \"dummy\";\n}\n"
    }
]
```

**Comment by yaegassy** [comment]
I changed the diagnostic-languageserver to verify this.

phpcbf seems to return 1 for "code".

**Comment by iamcco** [comment]
I add `ignoreExitCode` options support for formatter. it can be `true` ignore all exit code > 0 or `number[]` for exit codes you want to ignore. and below config works for me.

```
  "diagnostic-languageserver.formatters": {
    "phpcbf": {
      "command": "phpcbf",
      "rootPatterns": ["composer.lock", "vendor", ".git"],
      "args": [],
      "isStdout": true,
      "isStderr": false,
      "doesWriteToFile": false,
      "ignoreExitCode": [1]
    }
  },

```

**Comment by yaegassy** [comment]
I have confirmed that `phpcbf` works correctly in my environment with coc-diagnostic "v0.20.0". (add `"ignoreExitCode": [1]`)

**Comment by mkindred** [comment]
Confirmed working here, as well. Thanks!
