### ISSUE TITLE
Floating window not displaying diagnostic error

### ISSUE THREAD

**Issue by parker789** [iamcco/coc-diagnostic#4]
I'm trying my best here to configure coc.nvim because it seems like a fantastic solution.. but unfortunately I feel as though the documentation is still a bit spotty. I'm trying to have coc-diagonstic work as the screenshot show in the readme.. where the popup shows the error. 

Is there any way I can get the error to display in the popup? Right now mine only displays in the status line

**Comment by iamcco** [comment]
coc-diagnostic doesn't have the ability to let coc.nvim show the error in the popup. if you want coc.nvim to display error in the popup, be sure to use the latest neovim or vim. see the FAQ page of coc.nvim.

https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-make-preview-window-shown-aside-with-pum

**Comment by parker789** [comment]
hey @iamcco thanks for the super quick reply - i somewhat thought my neovim version would be the case, but thanks for confirming. while we're talking, can i piggy back here and ask why you think i might be seeing different eslint errors with coc-eslint + coc-diagnostic vs. just coc-eslint?

**Comment by iamcco** [comment]
You should just use coc-eslint or coc-diagnostic + eslint. I recommand use coc-eslint. coc-diagnostic just  offer the way to use linter with coc.nvim to display error.

**Comment by parker789** [comment]
ok cool, thanks! :)
