### ISSUE TITLE
How to use the formatter?

### ISSUE THREAD

**Issue by Moshem123** [iamcco/coc-diagnostic#42]
The details are not so clear to me.
I configured my `coc-settings.json` like this:
```
{
  ...
  "diagnostic-languageserver.filetypes": {
    "sh": "shellcheck"
  },
  "diagnostic-languageserver.formatters": {
    "tf": "terraform fmt",
    "terraform": "terraform fmt"
  },
  "diagnostic-languageserver.formatFiletypes": {
    "tf": "terraform fmt",
    "terraform": "terraform fmt"
  },
  ...
}
```

However, when opening a file that is recognized as terraform (`:set filetype?` echoes `filetype=terraform`), I don't understand how to format the file. I tried:
```
gggqG
```
it messes up the file.
```
gg=G
```
formats the file well, but not with the `terraform fmt` which also aligns the equals (`=`).

I tried also: `<Plug>(coc-format)` which is mapped to a key, nothing happens.

What am I doing wrong? Thanks.

**Comment by iamcco** [comment]
formatter examples: https://github.com/iamcco/diagnostic-languageserver/wiki/Formatters

Ues `<Plug>(coc-format)` or `:call CocAction('format')`

**Comment by Moshem123** [comment]
Alright, it was difficult to understand first, but now I get it!
For everyone googling, to format `terraform` files, you should add this to your `coc-settings.json`:
```
{
...
"diagnostic-languageserver.formatters": {
    "tffmt": {
      "command": "terraform",
      "args": ["fmt", "-"]
    }
  },
  "diagnostic-languageserver.formatFiletypes": {
    "terraform": "tffmt"
  }
...
}
```
