### ISSUE TITLE
run formatter on save

### ISSUE THREAD

**Issue by utrumo** [iamcco/coc-diagnostic#53]
How do I start any formatter. for example eslint --fix, which command to use? Can it be set to run automatically when file saved?

**Comment by iamcco** [comment]
If you want to use formatter, you can have a look of the formatter section at https://github.com/iamcco/diagnostic-languageserver. for automatically format on save then have a look at coc.nvim options, it has an option to do that.

**Comment by utrumo** [comment]
I set in coc-settings.json:
```
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "javascript.tsx",
    "javascriptreact",
    "typescript",
    "typescript.tsx",
    "typescriptreact"
  ],
  "diagnostic-languageserver.formatters": {
    "eslint-custom": {
      "command": "eslint_d",
      "rootPatterns": [
        ".git"
      ],
      "args": [
        "--stdin",
        "--stdin-filename",
        "%filepath",
        "--fix",
        "--fix-to-stdout"
      ],
      "isStderr": true,
      "isStdout": true
    }
  },
  "diagnostic-languageserver.formatFiletypes": {
    "javascript": "eslint-custom",
    "javascript.tsx": "eslint-custom",
    "javascriptreact": "eslint-custom",
    "typescript": "eslint-custom",
    "typescript.tsx": "eslint-custom",
    "typescriptreact": "eslint-custom"
  },
```
But It use only coc-prettier and  never start coc-diagnostic formatter.
What's i do wrong?

**Comment by utrumo** [comment]
@iamcco, I found a problem - it was conflict with coc-stylelintplus enableded with
`"stylelintplus.cssInJs": true` and `"stylelintplus.autoFixOnSave": true` options.

How can i use two formatters at one time (not necessarily coc-stylelintplus, but with at least two different formatters configured in coc-diagnostic) - run first one, then run second for single file -  stylelint and eslint for js files with react and css in js?

**Comment by iamcco** [comment]
I don't know, it's coc's behavior, it should be do in coc side.
