### ISSUE TITLE
Is it possible to replace just some aspects of a formatter or linter

### ISSUE THREAD

**Issue by expipiplus1** [iamcco/coc-diagnostic#54]
As a concrete example, I'd like to change *just* the `command` of `linters.shellcheck`, but if I have the following in my coc config I end up with a useless config (without all the other necessary options in `initializationOptions.linters.shellcheck`), also below.

```json
{
  "diagnostic-languageserver": {
    "linters": {
      "shellcheck": {
        "command": "/nix/store/7zddzbmfv7sd7138ybw4h9ayqg4j7qib-shellcheck-0.7.1-bin/bin/shellcheck"
      }
    }
  }
}
```

```json
    "initializationOptions": {
        "linters": {
            "shellcheck": {
                "command": "/nix/store/7zddzbmfv7sd7138ybw4h9ayqg4j7qib-shellcheck-0.7.1-bin/bin/shellcheck"
            },
...
```

I would expect that the default settings in `initializationOptions.linters.shellcheck` would be preserved.

**Comment by iamcco** [comment]
Not support yet.
