### ISSUE TITLE
I can't make it work with Standard (both linter and fixer)

### ISSUE THREAD

**Issue by gbrlsnchs** [iamcco/coc-diagnostic#6]
Hello, I have tested this extension with the `shellcheck` example and it worked well.

However, I'm trying to configure [Standard](https://standardjs.com/) with no success.

Here is my configuration for `coc-diagnostic`:
```json
// ...

  "diagnostic-languageserver.formatters": {
    "standard": {
      "command": "./node_modules/.bin/standard",
      "args": ["--stdin", "--fix"],
      "rootPatterns": [".git"],
      "isStderr": true,
      "isStdout": false
    }
  },
  "diagnostic-languageserver.linters": {
    "standard": {
      "command": "./node_modules/.bin/standard",
      "isStderr": true,
      "isStdout": false,
      "args": ["--stdin", "--verbose"],
      "rootPatterns": [".git"],
      "debounce": 100,
      "offsetLine": 0,
      "offsetColumn": 0,
      "sourceName": "standard",
      "formatLines": 1,
      "formatPattern": [
        "^\\s*<\\w+>:(\\d+):(\\d+):\\s+(.*)$",
        {
          "line": 1,
          "column": 2,
          "message": 3
        }
      ]
    }
  },
  "diagnostic-languageserver.filetypes": {
    "javascript": "standard",
    "javascript.jsx": "standard"
  },
  "diagnostic-languageserver.formatFiletypes": {
    "javascript": "standard",
    "javascript.jsx": "standard"
  },

// ...
```

I get no errors and no fixes on write with this config. I have tested the regex and it matches with messages output in stderr by Standard. Am I missing something?

**Comment by iamcco** [comment]
Change `isStderr` to false and `isStdout` to true.

**Comment by gbrlsnchs** [comment]
> Change `isStderr` to false and `isStdout` to true.

No success with the swap... still, Standard outputs data to stderr, I checked. I'm not sure why it's not working...

**Comment by iamcco** [comment]
It works for me. standard's output data have both stderr and stdout. stderr is for tips and stdout is for really data output.

**Comment by gbrlsnchs** [comment]
I just tried this out again and it worked. It might have been a mistake when configuring it in my old machine, but now everything is working fine! (I'm using it with `vim-lsp`, btw).

Thanks, I'm closing this.
