### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by PouriDev** [iamcco/coc-diagnostic#63]
Is there a way that I can customize Diagnostics? I want to show the diagnostics in front of the line like lspconfig, also I want to delete that >> sign. How can I do that? 

Also I want to show warning when a variable declared, but its value never used

**Comment by iamcco** [comment]
It can't not custom how the diagnostics look in the sign column. It's coc's behavior.

> Also I want to show warning when a variable declared, but its value never used

I don't know what does it mean. it can only send the linter's diagnostics to coc.

**Comment by PouriDev** [comment]
`variable declared, but its value never used` this kind of warning,

I've seen that we can do `cocdiagnostics.sign` something like this

**Comment by iamcco** [comment]
> variable declared, but its value never used this kind of warning,

warning/error and so on are defined by the linter, you can change the linter config to do that.

something like `ocdiagnostics.sign` are coc's config options.

**Comment by PouriDev** [comment]
How can I change linter config? Can you explain more about that? I'm interested/

**Comment by iamcco** [comment]
About linter config read the README of https://github.com/iamcco/diagnostic-languageserver.

> Also about that infront of the line diagnostics

If you mean the `>>` sign icon, you can change the coc option. read the doc of coc.

**Comment by PouriDev** [comment]
Ok, I've changed `>>` sign and it worked, but about that linter, I think Language Servers should do that, it isn't related to the linter  I think...

**Comment by iamcco** [comment]
> but about that linter, I think Language Servers should do that, it isn't related to the linter I think...

Read the linter config doc in  https://github.com/iamcco/diagnostic-languageserver. It's defined by the linter config.

**Comment by PouriDev** [comment]
I've read it, but didn't find anything useful, Can I show warnings like `variable declared but its value never used` with that?

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/100325714-f34ee080-3003-11eb-80ee-a36acda0d417.png)

You can only defined the kind of `variable declared but its value never used`'s security to warning. You can't only defined specify one to waring. If you want to defined the only `variable declared but its value never used` to warning you should config your linter to do that.
