### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by varac** [iamcco/coc-diagnostic#65]
Hi,

I'm new to coc. I'm missing an easy getting started guide for coc-diagnostic (i.e. what's the relation to https://github.com/iamcco/diagnostic-languageserver ?). I can't get coc-diagnostic to work based on the README.md of this project.
Do I need both projects to get it working ?

**Comment by iamcco** [comment]
You don't need to install diagnostic-languageserver.

Checkout the output channel if it does not work.

**Comment by varac** [comment]
Ok, I got coc-diagnostics setup at least for shellcheck now. 
I still don't get what's the difference between coc-diagnostic and diagnostic-languageserver, or what each project is for/best at ?

**Comment by iamcco** [comment]
coc-diagnostic is coc.nvim's extension that bundle with diagnostic-languageserver, so you don't need to install diagnostic-languageserver.
