### ISSUE TITLE
Add contributed formatters and linters to the default config

### ISSUE THREAD

**Issue by itaranto** [iamcco/coc-diagnostic#69]
It would be nice if every [formatter](https://github.com/iamcco/diagnostic-languageserver/wiki/Formatters) and [linter](https://github.com/iamcco/diagnostic-languageserver/wiki/Linters) were included in [config.ts](https://github.com/iamcco/coc-diagnostic/blob/master/src/config.ts).

**Comment by iamcco** [comment]
It open edit, any one can add new formatter and linter to the wiki. Need time to sync to config.ts

**Comment by iamcco** [comment]
Done

**Comment by itaranto** [comment]
Thanks!
