### ISSUE TITLE
vint not producing any suggestion

### ISSUE THREAD

**Issue by lelutin** [iamcco/coc-diagnostic#72]
**Describe the bug**
I've configured the "vim" filetype to use the "vint" linter but I'm not getting any hints about problems that vint would have found.

**To Reproduce**
coc-settings.json:

~~~
{
  "diagnostic-languageserver.filetypes": {
    "vim": "vint",
    "sh": "shellcheck"
  }
}
~~~

shellcheck *does* work, but vint doesn't

**Expected behavior**
On a file for which vint produces many warnings, I would expect to see hints about those warnings in the gutter

**Desktop (please complete the following information):**
 - OS: Debian unstable (sid), vim 8.2.1913-1 from the debian package

Log:

I'm not sure how I can obtain logs.

**Comment by lelutin** [comment]
ah, another detail: I've installed vint with:

~~~
pip install --user vim-vint
~~~

which installed it in `~/.local/bin/vint` and `~/.local/bin` is in my `PATH`

**Comment by iamcco** [comment]
Have a look at https://github.com/iamcco/coc-diagnostic/issues/62#issuecomment-735660297

**Comment by lelutin** [comment]
thanks, it started working after the commands in that comment :100:
