### ISSUE TITLE
When multiple PHPStan and PHP_CodeSniffer errors are on the same line, they are not all displayed

### ISSUE THREAD

**Issue by ngmy** [iamcco/coc-diagnostic#84]
**Describe the bug**
When multiple PHPStan and PHP_CodeSniffer errors are on the same line, they are not all displayed.

**To Reproduce**
1. Open the PHP file
2. Move the cursor to the error line

`~/.vim/coc-settings.json`:
https://github.com/ngmy/dotfiles/blob/aa0e0f105aa793213c680cf282d8557bc0469cb5/.vim/coc-settings.json

Composer scripts used in the `~/.vim/coc-settings.json`:
```json
"scripts": {
    "lint": [
        "@php tools/phpcs"
    ],
    "findbugs": [
        "@php tools/phpstan analyse --ansi"
    ],
}
```

**Expected behavior**
All PHPStan errors and PHP_CodeSniffer errors are shown.

**Screenshots**
When the cursor is on the `"a"`, some PHPStan errors are not shown.
![2021-03-23 (1)](https://user-images.githubusercontent.com/864041/112021328-88a64f80-8b74-11eb-8f13-5b41e1ccbd44.png)

When the cursor is on the `=`, all PHPStan errors are shown, but all PHP_CodeSniffer errors are not.
![2021-03-23](https://user-images.githubusercontent.com/864041/112021387-95c33e80-8b74-11eb-878a-d53379e6381c.png)

**Desktop (please complete the following information):**
Host machine:
 - OS: Ubuntu 20.04.1 LTS (WSL 2)
 - Vim: 8.1.2269
 - coc.nvim: 0.0.80-0a565835ea
 - Node.js: v14.15.1
 - coc-diagnostic: 0.18.1

Docker container:
 - OS: Ubuntu 18.04.5 LTS
 - PHP: 7.4.16
 - PHPStan:  0.12.80 (install by PHIVE)
 - PHP_CodeSniffer: 3.5.8 (install by PHIVE)

Log:

```
```

**Comment by iamcco** [comment]
Please setup `"diagnostic-languageserver.trace.server": "verbose"` to coc-settings.json then open output channel by `:CocCommand workspace.showOutput` and select diagnostic-languageserver.

**Comment by ngmy** [comment]
Is this enough?

```
[Trace - 11:36:36 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/nagamiya/localrepos/github.com/ngmy/php-observer/src/Subject.php",
    "diagnostics": [
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 14,
                    "character": 47
                },
                "end": {
                    "line": 14,
                    "character": 47
                }
            },
            "message": "There must be a single space between the colon and type in a return type declaration",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 14,
                    "character": 51
                },
                "end": {
                    "line": 14,
                    "character": 51
                }
            },
            "message": "Opening brace should be on a new line",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 15,
                    "character": 29
                },
                "end": {
                    "line": 15,
                    "character": 29
                }
            },
            "message": "Expected at least 1 space before \"=\"; 0 found",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 15,
                    "character": 29
                },
                "end": {
                    "line": 15,
                    "character": 29
                }
            },
            "message": "Expected at least 1 space after \"=\"; 0 found",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 15,
                    "character": 0
                },
                "end": {
                    "line": 16,
                    "character": 0
                }
            },
            "message": "Array (array<int, Ngmy\\Observer\\Observer>) does not accept key 'a'.",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 15,
                    "character": 0
                },
                "end": {
                    "line": 16,
                    "character": 0
                }
            },
            "message": "Array (array<int, Ngmy\\Observer\\Observer>) does not accept string.",
            "source": "src/Subject.php"
        }
    ]
}
```

The reported issue occurred in line 15.

**Comment by yaegassy** [comment]
@ngmy 

> When multiple PHPStan and PHP_CodeSniffer errors are on the same line, they are not all displayed

Does this problem only occur with multiple configurations?

Does it behave as expected when using only `phpcs` or `phpstan`?

It is possible that one of the settings may need to be adjusted. (e.g. Adjustable by `offsetLine` or `offsetColumn` setting)

**Comment by iamcco** [comment]
> Is this enough?
> 
> ```
> [Trace - 11:36:36 PM] Received notification 'textDocument/publishDiagnostics'.
> Params: {
>     "uri": "file:///home/nagamiya/localrepos/github.com/ngmy/php-observer/src/Subject.php",
>     "diagnostics": [
>         {
>             "severity": 1,
>             "range": {
>                 "start": {
>                     "line": 14,
>                     "character": 47
>                 },
>                 "end": {
>                     "line": 14,
>                     "character": 47
>                 }
>             },
>             "message": "There must be a single space between the colon and type in a return type declaration",
>             "source": "src/Subject.php"
>         },
>         {
>             "severity": 1,
>             "range": {
>                 "start": {
>                     "line": 14,
>                     "character": 51
>                 },
>                 "end": {
>                     "line": 14,
>                     "character": 51
>                 }
>             },
>             "message": "Opening brace should be on a new line",
>             "source": "src/Subject.php"
>         },
>         {
>             "severity": 1,
>             "range": {
>                 "start": {
>                     "line": 15,
>                     "character": 29
>                 },
>                 "end": {
>                     "line": 15,
>                     "character": 29
>                 }
>             },
>             "message": "Expected at least 1 space before \"=\"; 0 found",
>             "source": "src/Subject.php"
>         },
>         {
>             "severity": 1,
>             "range": {
>                 "start": {
>                     "line": 15,
>                     "character": 29
>                 },
>                 "end": {
>                     "line": 15,
>                     "character": 29
>                 }
>             },
>             "message": "Expected at least 1 space after \"=\"; 0 found",
>             "source": "src/Subject.php"
>         },
>         {
>             "severity": 1,
>             "range": {
>                 "start": {
>                     "line": 15,
>                     "character": 0
>                 },
>                 "end": {
>                     "line": 16,
>                     "character": 0
>                 }
>             },
>             "message": "Array (array<int, Ngmy\\Observer\\Observer>) does not accept key 'a'.",
>             "source": "src/Subject.php"
>         },
>         {
>             "severity": 1,
>             "range": {
>                 "start": {
>                     "line": 15,
>                     "character": 0
>                 },
>                 "end": {
>                     "line": 16,
>                     "character": 0
>                 }
>             },
>             "message": "Array (array<int, Ngmy\\Observer\\Observer>) does not accept string.",
>             "source": "src/Subject.php"
>         }
>     ]
> }
> ```
> 
> The reported issue occurred in line 15.

It's the diagnostics amount correct in the log ?

**Comment by iamcco** [comment]
Is that you want to show all errors at the same line ? if that is then checkout option `"diagnostic.checkCurrentLine": true`

**Comment by ngmy** [comment]
@iamcco 
> It's the diagnostics amount correct in the log ?

Yes. The diagnostic results in the log are correct. I want to see them all.

I try to organize the issue.

Log: 
```
[Trace - 9:41:44 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/nagamiya/localrepos/github.com/ngmy/php-observer/src/Subject.php",
    "diagnostics": [
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 29
                },
                "end": {
                    "line": 17,
                    "character": 29
                }
            },
            "message": "Expected at least 1 space before \"=\"; 0 found",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 29
                },
                "end": {
                    "line": 17,
                    "character": 29
                }
            },
            "message": "Expected at least 1 space after \"=\"; 0 found",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 0
                },
                "end": {
                    "line": 18,
                    "character": 0
                }
            },
            "message": "Array (array<int, Ngmy\\Observer\\Observer>) does not accept key 'a'.",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 8
                },
                "end": {
                    "line": 17,
                    "character": 8
                }
            },
            "message": "$this->observers with declared type 'list<Ngmy\\Observer\\Observer>' cannot be assigned type 'non-empty-array<\"a\"|int, Ngmy\\Observer\\Observer>'",
            "source": "src/Subject.php"
        }
    ]
}
```

Errors that is occurring:
| error | start.line | start.character | end.line | end.character | description |
| --- | --- | --- | --- | --- | --- |
| 1 | 17 | 29 | 17 | 29 | phpcs error. |
| 2 | 17 | 29 | 17 | 29 | phpcs error. |
| 3 | 17 | 0 | 18 | 0 | phpstan error. | 
| 4 | 17 | 8 | 17 | 8 | psalm error. |

View in my Vim:
| line | character |
| 18 | 1 |
| 18 | 2 |
| 18 | 2 |
| 18 | 2 |
| 18 | 2 |
| 18 | 2 |
| 18 | 2 |
| 18 | 2 |
| 18 | 2 |
| 18 | 2 |

**Comment by ngmy** [comment]
@iamcco 
> It's the diagnostics amount correct in the log ?

Yes. The diagnostic results in the log are correct. I want to see them all.

I try to organize the issue.

Log: 
```
[Trace - 9:41:44 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/nagamiya/localrepos/github.com/ngmy/php-observer/src/Subject.php",
    "diagnostics": [
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 29
                },
                "end": {
                    "line": 17,
                    "character": 29
                }
            },
            "message": "Expected at least 1 space before \"=\"; 0 found",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 29
                },
                "end": {
                    "line": 17,
                    "character": 29
                }
            },
            "message": "Expected at least 1 space after \"=\"; 0 found",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 0
                },
                "end": {
                    "line": 18,
                    "character": 0
                }
            },
            "message": "Array (array<int, Ngmy\\Observer\\Observer>) does not accept key 'a'.",
            "source": "src/Subject.php"
        },
        {
            "severity": 1,
            "range": {
                "start": {
                    "line": 17,
                    "character": 8
                },
                "end": {
                    "line": 17,
                    "character": 8
                }
            },
            "message": "$this->observers with declared type 'list<Ngmy\\Observer\\Observer>' cannot be assigned type 'non-empty-array<\"a\"|int, Ngmy\\Observer\\Observer>'",
            "source": "src/Subject.php"
        }
    ]
}
```

Errors that is occurring:
| Error | Start Line | Start Character | End Line | End Character | Description |
| --- | --- | --- | --- | --- | --- |
| 1 | 17 | 29 | 17 | 29 | phpcs error. |
| 2 | 17 | 29 | 17 | 29 | phpcs error. |
| 3 | 17 | 0 | 18 | 0 | phpstan error. | 
| 4 | 17 | 8 | 17 | 8 | psalm error. |

Display status in my Vim:
✔️: Displayed
➖: Not Displayed
⚠️: Displayed, but it is cut off in the middle

`"diagnostic.checkCurrentLine": false`
| Line | Character | Error 1| Error 2 | Error 3 | Error 4 | Expected or Not expected |
| --- | --- | --- | --- | --- | --- | --- |
| 18 | 1 | ➖  | ➖ | ✔️  | ➖ | Expected. |
| 18 | 2 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 3 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 4 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 5 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 6 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 7 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 8 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 9 | ➖ | ➖ | ✔️ | ⚠️ | Not expected. Error 4 is cut off in the middle. | 
| 18 | 10 | ➖ | ➖ | ✔️ | ⚠️ | Not expected. Error 4 is cut off in the middle. | 
| 18 | 11 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 12 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 13 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 14 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 15 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 16 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 17 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 18 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 19 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 20 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 21 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 22 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 23 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 24 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 25 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 26 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 27 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 28 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 29 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 30 | ➖ | ✔️ | ✔️ | ➖ | Not expected. Error 1 is not displayed. |
| 18 | 31 | ➖ | ✔️ | ✔️ | ➖ | Not expected. Error 1 is not displayed. |
| 18 | 32 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 33 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 34 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 35 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 36 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 37 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 38 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 39 | ➖ | ➖ | ✔️ | ➖ | Expected. |
| 18 | 40 | ➖ | ➖ | ✔️ | ➖ | Expected. |

`"diagnostic.checkCurrentLine": true`
| Line | Character | Error 1| Error 2 | Error 3 | Error 4 | Expected or Not expected |
| --- | --- | --- | --- | --- | --- | --- |
| 18 | 1 | ➖ | ➖ | ✔️  | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 2 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 3 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 4 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 5 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 6 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 7 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 8 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 9 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 10 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 11 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 12 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 13 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 14 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 15 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 16 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 17 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 18 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 19 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 20 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 21 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 22 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 23 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 24 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 25 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 26 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 27 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 28 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 29 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 30 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 31 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 32 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 33 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 34 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 35 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 36 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 37 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 38 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 39 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |
| 18 | 40 | ➖ | ➖ | ✔️ | ✔️ | Not expected. Error 1 and 2 are not displayed. |

@yaegassy 
> Does it behave as expected when using only phpcs or phpstan?

If I use only phpcs, error1 is not displayed. 
I expect error 1 and 2 to be displayed.

I copied and pasted the code on the same line so that I get two error 3s on the same line.
And then if I use only phpstan, two error 3 are displayed, but the second one was cut off in the middle.

----

I think there are two issues as follows:
- When there are multiple errors for the same character, only the last error is displayed
- If the error is too long, it will be cut off in the middle

**Comment by iamcco** [comment]
> Yes. The diagnostic results in the log are correct. I want to see them all.

seems like coc.nvim issue. this extension doesn't control display.

**Comment by ngmy** [comment]
> seems like coc.nvim issue. this extension doesn't control display.

Ah, I see.
Now I understand that the issue is on the coc.nvim side.

**Comment by ngmy** [comment]
By upgrading Vim to 8.2 and adding [this](https://github.com/neoclide/coc.nvim/commit/81898745399904f16e1aa2caaf586a49f5422c40) to the configuration of coc.nvim, I was able to make the float window scrollable and show all errors.
