### ISSUE TITLE
High cpu usage with pylint

### ISSUE THREAD

**Issue by matheusfillipe** [iamcco/coc-diagnostic#87]
Relevant part of coc-config.json
``` 
  "diagnostic-languageserver.filetypes": {
    "python": "pylint",
    "vim": "vint",
    "email": "languagetool",
    "markdown": [ "write-good", "markdownlint" ],
    "sh": "shellcheck",
    "elixir": ["mix_credo", "mix_credo_compile"],
    "eelixir": ["mix_credo", "mix_credo_compile"],
    "php": ["phpstan", "psalm"]
  },
  "diagnostic-languageserver.linters": {
    "pylint": {
      "sourceName": "pylint",
      "command": "pylint",
      "args": [
        "--output-format",
        "text",
        "--score",
        "no",
        "--msg-template",
        "'{line}:{column}:{category}:{msg} ({msg_id}:{symbol})'",
        "%file"
      ],
      "formatPattern": [
        "^(\\d+?):(\\d+?):([a-z]+?):(.*)$",
        {
          "line": 1,
          "column": 2,
          "security": 3,
          "message": 4
        }
      ],

```

it seems it starts a pylint process on every keytroke. Can I reduce this only to once when normal mode somehow?

**Comment by iamcco** [comment]
> Can I reduce this only to once when normal mode somehow?

Not support yet. you can add `debounce` to your linter config.

**Comment by matheusfillipe** [comment]
Thanks! I was not sure what debounce was exactly, is it a min time in ms to ignore pylint calls? Something like that I guess. So I trying setting it up to 500 1000 but still seemed that pylint itself was too processor intensive. 

I switched to flake8 now and seems it is way less cpu intensive. I am testing for a while and no annoying cpu fan noise!
