### ISSUE TITLE
stylelint doesn't find .stylelintrc

### ISSUE THREAD

**Issue by davidosomething** [iamcco/coc-diagnostic#9]
Using default options, stylelint doesn't find the .stylelintrc in project git root,
how might I configure this?

**Comment by iamcco** [comment]
It's weird, it works for me. My .stylelintrc also in git root.

try to copy the linter's config and add the `--config` options:


``` jsonc
  "diagnostic-languageserver.linters": {
    "stylelint": {
      "command": "./node_modules/.bin/stylelint",
      "rootPatterns": [".git"],
      "isStdout": true,
      "isStderr": false,
      "debounce": 100,
      "args": ["--config", "./path-to-config/.stylelintrc", "--formatter",  "unix"],
      "offsetLine": 0,
      "offsetColumn": 0,
      "sourceName": "stylelint",
      "formatLines": 1,
      "formatPattern": [
        "^[^:]+:(\\d+):(\\d+):\\s(.+)\\s\\[(\\w+)\\]$",
        {
          "line": 1,
          "column": 2,
          "message": 3,
          "security": 4
        }
      ],
      "securities": {
        "error": "error",
        "warning": "warning"
      }
    }
  },
```

**Comment by davidosomething** [comment]
sorry, that didn't work
I have the config path to `./stylelintrc` since it is in the top level

in variables.css i have:

```css
@value background: #fcfcfc;
@value subBackground: #faf8f6;
... more css-modules values
```

in .stylelintrc:
```
{
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-css-modules"
  ]
}
```

in package.json
```
...
  "devDependencies": {
    "prettier": "^1.18.2",
    "stylelint": "^11.1.1",
    "stylelint-config-css-modules": "^1.5.0",
    "stylelint-config-recommended": "^3.0.0"
  }
...
```

coc-diagnostic is reporting
![image](https://user-images.githubusercontent.com/609213/66724407-c33e8100-edf3-11e9-8df1-6e7a342bc965.png)

those unknown value rule warnings


as an aside, the stylelint config is read and working properly if i use `npx stylelint` from command line or neomake

**Comment by iamcco** [comment]
The Warning from the picture is not from coc-diagnostic.

coc-diagnostic's report is like below:

![image](https://user-images.githubusercontent.com/5492542/66727404-7bf6d580-ee71-11e9-9c17-8b5a3cc27735.png)

**Comment by davidosomething** [comment]
OH! You are right, this is from `coc-css`!
