### ISSUE TITLE
Adapting the color scheme for severity levels? 

### ISSUE THREAD

**Issue by iselind** [iamcco/coc-diagnostic#98]
I need to change the colors used for different severity levels to make the text readable. I cannot find how to do this. I assume it's a setting in `~/.vim/coc-settings.json`.

At the moment I have put in place a workaround where I simply skip the severity level mapping for the diagnostic tools I need that produce the problem. One of them is shellcheck (specifically the `[shellcheck] [I]` issues) using the settings directly copied from the settings example in this repository. I do feel it's a shame to drop the severity levels, but I value being able to read the linter's feedback more.

Perhaps it would be possible to reuse nvim's color scheme to a larger extent than today? I get the feeling the colors used are hard coded and does not take the current color scheme into account.

**Comment by iamcco** [comment]
It's coc.nvim config, `:h coc-highlights`
